// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:7884cd53-065b-411a-81a2-0eb504ac0ee1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_FKODNHb1z',
  aws_user_pools_web_client_id: '18ogml7lldl7kk0ucilqgf662b',
}

export default awsmobile
