// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b15afc8f-41dc-4ff3-8fec-eaba4e1e9e82",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_60JczhZUD",
    "aws_user_pools_web_client_id": "6s2mk8nkfgg4gkrq7if1u83pk6"
};


export default awsmobile;
